# Default values for soil.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deployment:
  replicaCount: 1

container:
  port: 8080

image:
  repository: formicarium/soil
  tag: dfa95776dc66f22f163a7dfaecb41490b4342053 #aea104762e7dbeca6cab64f6e8045351c6182657

service:
  port: 80

ingress:
  enabled: true
  tld: formicarium.host
