{{- if .Values.ingress.enabled -}}
{{- $name := include "hive.name" . -}}
{{- $tld := .Values.ingress.tld }}
{{- $namespace := .Release.Namespace }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $name }}
  labels:
    app: {{ $name }}
    chart: {{ template "hive.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    tier: backend
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/ssl-redirect: "true"
    nginx.org/ssl-services: {{ $name | quote }}
    kubernetes.io/tls-acme: "true"
spec:
  tls:
    - hosts:
      - "{{ $name }}.{{ $namespace }}.{{ $tld }}"
      secretName: {{ $name }}-certificate
  rules:
  - host: "{{ $name }}.{{ $namespace }}.{{ $tld }}"
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ $name }}
          servicePort: http
{{- end }}