{{- if .Values.ingress.enabled -}}
{{- $name := include "soil.name" . -}}
{{- $tld := .Values.ingress.tld }}
{{- $namespace := .Release.Namespace }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $name }}
  labels:
    app: {{ $name }}
    chart: {{ template "soil.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    tier: backend
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: "{{ $name }}.{{ $tld }}"
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ $name }}
          servicePort: http
{{- end }}
