{{- $name := include "soil.name" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  labels:
    app: {{ $name }}
    chart: {{ template "soil.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    tier: backend
spec:
  ports:
    - port: {{ .Values.service.port }}
      name: http
      targetPort: http
      protocol: TCP
  selector:
    app: {{ $name }}
    release: {{ .Release.Name }}