# Default values for hive.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deployment:
  replicaCount: 1

container:
  port: 8080

image:
  repository: formicarium/hive
  tag: 31ba77ad823ac93c766dcb15f9162bf57f585a27

service:
  port: 80

ingress:
  enabled: true
  tld: formicarium.host